### ISSUE TITLE
Support memory-mapped packed file for rating data

### ISSUE THREAD

**Issue by ghost** [lenskit/lenskit#101]
(originally reported in Trac by @elehack on 2011-06-22 22:14:49)

We would like to create packed binary files of rating data to support more efficient evaluation (using less Java heap, more efficient disk usage, etc.).

Therefore, we want to implement a rating DAO that packs data into three binary files, with the following proposed structure:

* A master file of ratings data, of the form (user, item, rating, timestamp), sorted by timestamp.
* User and item index files. Each of these files has two parts. The first part is user (resp. item) entries, sorted by user (resp. item) ID; each entry is an ID and an offset. The offset records where in the file the user's (resp. item's) ratings are stored. At the offset, there is the number of ratings, followed by the positions in the master file of each of the user's ratings, in timestamp order.

The master file is simple. The user file format is more complicated. The proposed structure:

    NUSERS:INT4
    (USER:INT8 OFFSET:INT4) * NUSERS
    (NRATINGS:INT4 
     INDEX:INT4 * NRATINGS) * NUSERS

We may want to consider 64-bit offsets & indices, to allow bigger files and help with data alignment, but that will take more space. We can deal with alignment issues, if they come up, with padding (4-byte padding after nusers, 4-byte padding in each user).

We may need to make the user list part of the user file a B-tree rather than a list, depending on how user search performance is. Let's implement the simple version first, though, and then test if it is too slow.

**Note**: This issue has been automatically migrated from Bitbucket
Created by [grouplens](https://bitbucket.org/grouplens) on 2013-02-01T21:58:28.378694+00:00, last updated: 2013-07-19T21:53:43.501279+00:00

**Comment by elehack** [comment]
This was done by #482.
