### ISSUE TITLE
which algorithm does use the item feature(e.g. some features in ML-100k's u.item files) in Lenskit

### ISSUE THREAD

**Issue by kyowill** [lenskit/lenskit#1023]

**Comment by mdekstrand** [comment]
LensKit does not currently include any algorithms which make use of that data.

However, that data will be used by the command-line tools (`recommend` and `predict`) to display item titles with their results.

**Comment by kyowill** [comment]
If data isn't based on ML-100k's u.item files, how does the Lenskit calculate  item similarity  in ItemCF ?

**Comment by mdekstrand** [comment]
Item similarity in collaborative filtering is based solely on user-item rating patterns.
