### ISSUE TITLE
Adding Parameter to IntelliJ IDEA 

### ISSUE THREAD

**Issue by MohammadAvrahem** [lenskit/lenskit#1064]
Hello everyone, 

While i was watching the tutorial, the tutor said that i have to build the program using Maven build. On IntelliJ IDAE>Edit Configurations>Maven build.

Then he suggests to add Maven goal, which by the way i did, and i set it to "lenskit-eval". Then he said that we should add parameters in order to determine that we are downloading data for non-commercial use, but i am not sure how to do that on IntelliJ IDEA, although it's much easier on Eclipse?

Thank you for reading anyway!

**Comment by mdekstrand** [comment]
It sounds like the tutorial you are looking at is very old.
