### ISSUE TITLE
Make evaluations restartable

### ISSUE THREAD

**Issue by ghost** [lenskit/lenskit#112]
(originally reported in Trac by @elehack on 2011-08-02 19:56:10)

Sometimes, processes die for various reasons.  We should devise a means of making evaluations checkpointable and restartable.

**Note**: This issue has been automatically migrated from Bitbucket
Created by [grouplens](https://bitbucket.org/grouplens) on 2013-02-01T21:58:41.903230+00:00, last updated: 2013-02-01T22:35:33.399781+00:00

**Comment by mdekstrand** [comment]
Cache support really takes care of this, I think.
