### ISSUE TITLE
Support TemporalMAE and ProfileMAE

### ISSUE THREAD

**Issue by ghost** [lenskit/lenskit#13]
(originally reported in Trac by @elehack on 2011-03-16 22:30:36)

The evaluator needs to support Burke's TemporalMAE and ProfileMAE metrics.

**Note**: This issue has been automatically migrated from Bitbucket
Created by [grouplens](https://bitbucket.org/grouplens) on 2013-02-01T21:38:43.416145+00:00, last updated: 2013-02-01T22:35:45.014660+00:00

**Comment by elehack** [comment]
This is supersceded by #663.
