### ISSUE TITLE
Allow evaluation tasks to be run in parallel

### ISSUE THREAD

**Issue by ghost** [lenskit/lenskit#165]
(originally reported in Trac by @shilad on 2012-04-01 17:51:22)

Once #161 is completed it would be fantastic to add support for parallelism of tasks. A loop-like construct with a fixed # worker threads would do the trick for me.

I have no idea how difficult this would be, but it would be very useful.

**Note**: This issue has been automatically migrated from Bitbucket
Created by [grouplens](https://bitbucket.org/grouplens) on 2013-02-01T22:06:10.601410+00:00, last updated: 2013-06-20T15:42:27.759225+00:00

**Comment by mdekstrand** [comment]
This will be the responsibility of Gradle. The evaluator will be parallelized, but in different ways.
