### ISSUE TITLE
Support evaluation of implicit feedback recommenders

### ISSUE THREAD

**Issue by ghost** [lenskit/lenskit#256]
We want to be able to evaluate implicit feedback recommenders using P@N and similar metrics.

Several pieces:
- support cross-folding of unary data sets
- support generating unary data sets
- support Top-N metrics that work without ratings
- make sure recommend-only evaluation works

**Note**: This issue has been automatically migrated from Bitbucket
Created by @elehack on 2013-02-20T20:16:29.935306+00:00, last updated: 2013-07-19T21:52:12.317658+00:00

**Comment by mdekstrand** [comment]
Hey, we can do this now! Except for cross-folding.
