### ISSUE TITLE
Make greater use of checked exceptions

### ISSUE THREAD

**Issue by ghost** [lenskit/lenskit#267]
Right now, recommender component builders cannot throw checked exceptions; they must throw unchecked exceptions as they are `Provider`s. It would be nice to introduce better exception handling!

A potential future refinement is to add checked exceptions to the public recommend interfaces, since they can routinely fail.

Round 1 pieces (should be compatible with compatibility guarantees):

- Enhance Grapht to allow arbitrary provider-like interfaces to be used.
- Introduce a `LenskitComponentBuilder` interface with a `build()` method that throws a checked exception.
- Make all component builders implement `LenskitComponentBuilder`

Round 2 pieces (breaking changes):

- Make public methods on recommender components throw a checked exception
- Propagate other checked exceptions more thoroughly to raise these exceptions

If we do this, we might want to accelerate plans for LensKit 2.0.

**Note**: This issue has been automatically migrated from Bitbucket
Created by @elehack on 2013-02-27T16:36:32.765276+00:00, last updated: 2013-08-31T22:34:12.501673+00:00

**Comment by elehack** [comment]
We may not want to do this: http://literatejava.com/exceptions/checked-exceptions-javas-biggest-mistake/

**Comment by mdekstrand** [comment]
We will not be moving to checked exceptions; instead, we will move to unchecked exceptions. I will file a separate bug for that.
