### ISSUE TITLE
Provide command to perform generic actions on algorithms

### ISSUE THREAD

**Issue by ghost** [lenskit/lenskit#290]
Besides the `trainTest`, it would be nice to make it easy to do arbitrary things to algorithms, such as extract the model and serialize it.

I want to add a `withRecommender` command that allows arbitrary actions to be used:

```groovy
withRecommender {
    algorithm algo
    data inputData
    action {
        // some groovy code
    }
}
```

This command will run `action` bound to a recommender, trained and opened on the input data.

This is distinct from #250; that ticket pertains to arbitrary inspections of models in train-test configurations, while this just trains a model and lets it be inspected

**Note**: This issue has been automatically migrated from Bitbucket
Created by @elehack on 2013-04-02T20:31:36.091227+00:00, last updated: 2013-04-12T16:18:18.532993+00:00

**Comment by elehack** [comment]
Going to call this done since we're moving to the command line.
