### ISSUE TITLE
Build LensKit evaluator on top of Gradle

### ISSUE THREAD

**Issue by ghost** [lenskit/lenskit#296]
The LensKit evaluator grows features and will likely keep growing features. Many of its needs are similar to various build tools.

It is worthwhile investigating whether the evaluator would be best integrated with an existing build tool such as [Gradle](http://www.gradle.org/) to harness the work they are already doing, rather than re-inventing incompatible work.

We already integrate with Maven, but doing very much in Maven is very cumbersome and often results in falling back to Ant.

Using Gradle has a number of advantages:

- Easy to do arbitrary actions (important for experimentation)
- Uses SLF4J with Logback for logging, so logging is cleanly integrated with LensKit and Grapht
- Sufficiently flexibility to let us route data around like we want to in almost all cases

**Note**: This issue has been automatically migrated from Bitbucket
Created by @elehack on 2013-04-16T17:15:50.791917+00:00, last updated: 2013-06-27T22:33:03.876083+00:00

**Comment by mdekstrand** [comment]
This is now finally done.
