### ISSUE TITLE
Render graphs in pure Java

### ISSUE THREAD

**Issue by ghost** [lenskit/lenskit#318]
I would like to render graphs in pure Java, using something like [JGraphX](http://www.jgraph.com) or rendering SVG directly, so that we don't need the GraphViz binary, we can include legends, and are moved in the direction of building a GUI.

**Note**: This issue has been automatically migrated from Bitbucket
Created by @elehack on 2013-05-22T20:38:53.191258+00:00, last updated: 2013-08-31T21:43:13.784557+00:00

**Comment by mdekstrand** [comment]
[Viz.js](https://github.com/mdaines/viz.js) will fix this nicely!
