### ISSUE TITLE
Provide user rating vector DAO

### ISSUE THREAD

**Issue by ghost** [lenskit/lenskit#341]
It would be useful to provide a user rating vector DAO, so that optimized versions can extract user rating vectors directly from storage.

The default implementation will use the user event DAO and a history summarizer.

**Note**: This issue has been automatically migrated from Bitbucket
Created by @elehack on 2013-07-24T19:37:35.910387+00:00, last updated: 2013-08-31T21:42:25.992704+00:00

**Comment by mdekstrand** [comment]
I think it would be better to expose this as a ratings matrix (#715).
