### ISSUE TITLE
Read properties from properties file in evaluator

### ISSUE THREAD

**Issue by ghost** [lenskit/lenskit#359]
We should allow the evaluator to read properties from a properties file, not just the command line, to ease configuration.

It should automatically read `eval.properties`.

**Note**: This issue has been automatically migrated from Bitbucket
Created by @elehack on 2013-09-20T17:30:49.711349+00:00

**Comment by elehack** [comment]
I'm not sure this will really be relevant in the new design.

**Comment by elehack** [comment]
Actually, I'm fairly sure it won't be. The new evaluator will run mostly on generated files, so this is less relevant. We might want a way to feed properties into algorithm configurations, but that is it.
