### ISSUE TITLE
Populate DAOs using a DB table

### ISSUE THREAD

**Issue by sandakith** [lenskit/lenskit#386]
I have seen how lenskit use dependency injection to populate DAOs using a CVS file.
       LenskitConfiguration config = new LenskitConfiguration();
        // configure the rating data source
        config.bind(EventDAO.class)
              .to(MOOCRatingDAO.class);
        config.set(RatingFile.class)
              .to(new File("data/ratings.csv"));

Is there a way to populate DAOs using a DB table. This feature may already available. 
But could not find any documentation or sample code.

**Comment by jjkayani** [comment]
Hi mdekstrand, how to fetch the data of other tables other than ratings, like items table or item tags tables?

**Comment by mdekstrand** [comment]
@jjkayani The way to do it currently (for LensKit 3) is to create your own implementation of `DataAccessObject` that is backed by your database.

We are planning to provide a default JDBC DAO again, but have not yet had time to get that done.
