### ISSUE TITLE
Implement parallel item-item similarity computation strategy

### ISSUE THREAD

**Issue by ghost** [lenskit/lenskit#5]
(originally reported in Trac by @elehack on 2011-03-16 22:22:19)

Item-item similarity computation can be parallelized by writing a new similarity matrix build strategy.  We should do this.

**Note**: This issue has been automatically migrated from Bitbucket
Created by [grouplens](https://bitbucket.org/grouplens) on 2013-02-01T21:38:28.772959+00:00, last updated: 2013-02-01T22:35:45.926735+00:00

**Comment by mdekstrand** [comment]
Obsoleted by #724.
