### ISSUE TITLE
Use pre-sorting to reduce memory load in top-N diversity metrics

### ISSUE THREAD

**Issue by mdekstrand** [lenskit/lenskit#520]
The `computePop` method of [TopNPopularityMetric](https://github.com/lenskit/lenskit/blob/master/lenskit-eval/src/main/java/org/grouplens/lenskit/eval/metrics/topn/TopNPopularityMetric.java#L72) currently uses a great deal of memory and time, building an items x users map to compute how many distinct users rated each item.

This can be rewritten to use a sorting version of `streamRatings`, streaming ratings by item ID instead of the default order. With this change, all of an item's ratings (and therefore users) will appear together; the code will only need to keep track of the users being who rated the current item, rather than the users that rated all items.

**Comment by elehack** [comment]
If practical, it would be very nice to have some tests for this class before modifying it.

**Comment by mdekstrand** [comment]
Since `rating` entities aren't duplicated, we can be even simpler :smile: - we don't need to count distinct users, just ratings-per-item.

**Comment by mdekstrand** [comment]
Let's *not* pre-sort. Just maintain an item counter & process in any order, or just grab the items out of the `RatingSummary`.

**Comment by mdekstrand** [comment]
This has already been done via `RatingSummary`.
