### ISSUE TITLE
Implement a rating summary and associated provider

### ISSUE THREAD

**Issue by mdekstrand** [lenskit/lenskit#546]
I'd like to have a `GlobalMeanRatingProvider` that provides the global mean rating (as a `Double`), and use it as the default provider for a `@GlobalMean` annotation. This will allow components to obtain the global mean without recomputing it.

We can similarly have an `ItemMeanRatingProvider` that provides a table of item means.

This should then be used in the global and item mean rating scorers.

**Comment by elehack** [comment]
Let's put them in the `org.grouplens.lenskit.data.summary` package in the `lenskit-core` module.

**Comment by elehack** [comment]
The basic logic for the summary builder is already in `ItemMeanRatingItemScorer`

**Comment by mdekstrand** [comment]
Implemented this with the major 3.0-T1 upgrades.
