### ISSUE TITLE
Standardize builder/factory/provider language

### ISSUE THREAD

**Issue by mdekstrand** [lenskit/lenskit#552]
Right now, we use `FooBuilder` both for a class exposing an API to build a complex `Foo`, and for building model objects.

The latter, since they mostly just get their `get` method called and are configured via the constructor, should possibly be called `FooFactory`.

In general, we should be consistent and comprehensible in our usage of the terms *builder*, *factory*, and *provider*.

**Comment by mdekstrand** [comment]
Proposal:

- Introduce `ComponentFactory` interface and `@DefaultFactory` annotation, and make them equivalent to a `Provider` and `@DefaultProvider`, except higher-priority.
- Call model builders model *factories*. It's weird to call this expensive building process a 'provider', in my opinion.
- Use `javax.inject.Provider`s for lightweight dynamic provision, rather than expensive model building.
- Reserve the ‘builder’ terminology for Effective Java 2-style object builders, where we're just setting up the contents of an object to be built and are operating outside of the DI context. This is more consistent with general use of 'builder', as well as some other LensKit use of the term.

The downside I see to this strategy is the overlap between ‘factory’ and ‘provider’. Maybe it's OK to have an `ItemItemModelProvider` that does an expensive build process.

@kluver, thoughts?

**Comment by kluver** [comment]
What actual value does this work give us? Ive never had confusion around these points as factories and provides seem to fill the same role of being an object that causes an object.

In general I want to avoid duplication, especially meta-level duplication.

**Comment by mdekstrand** [comment]
Avoiding duplication is good, and explaining the difference between a provider and a factory is probably not worthwhile, especially since there is no actual difference in how they are used.

So, standardize on 'Provider' language and rename all our 'model builders' to be 'model providers', and go with that?

**Comment by kluver** [comment]
That works for me.

**Comment by mdekstrand** [comment]
Will do.

**Comment by mdekstrand** [comment]
I have renamed all of our builders that should be providers in #941. Done.
