### ISSUE TITLE
Write a Known rating rating predictor

### ISSUE THREAD

**Issue by kluver** [lenskit/lenskit#563]
Currently there is no way to easily make lenskit return known ratings when asked to predict an item with a known rating.

An easy solution would be a custom RatingPredictor that takes a fallback scorer or predictor, but returns ratings from the DAO if any are available.

Some further notes:

- should be in the `lenskit-predict` module
- should be called `KnownRatingRatingPredictor`
- will depend on a `UserEventDAO`, get the user's rating events from the DAO
- will score using the user's existing ratings

**Comment by elehack** [comment]
I've seen initial code for this, it looks like it will land for 2.2.
