### ISSUE TITLE
Provide setThreadCount API for SimpleEvaluator

### ISSUE THREAD

**Issue by mdekstrand** [lenskit/lenskit#570]
Right now, it's nonobvious how to set the thread count for the simple evaluator. Would be good to add a `setThreadCount` API.

This will set the appropriate property in the `EvalConfig`.

**Comment by elehack** [comment]
What needs to happen for this: add a method `public void setThreadCount(int nthreads)` to `SimpleEvaluator`; this method will set a property in the `EvalConfig` to specify the number of threads that the evaluator should use.

**Comment by mdekstrand** [comment]
This is even easier now that we have the new train-test design.

**Comment by mdekstrand** [comment]
Do it on the `TrainTestExperiment`.
