### ISSUE TITLE
Configuration scripts loaded with custom classpath do not work

### ISSUE THREAD

**Issue by elehack** [lenskit/lenskit#660]
If I load a configuration script with a custom classpath (`-C`), it cannot reference classes on the custom classpath.

**Comment by elehack** [comment]
This bug is nasty and blocks easy homework publication.

**Comment by kluver** [comment]
I don't know if this is a good idea or not, but while you're fixing this how hard would it be to add some sort of eval script command to add a directory to the classpath. This would make it easier to not need the classpath flag on the CLI (since that information can be embedded in the script)

**Comment by elehack** [comment]
@kluver Pretty difficult, actually. I don't think class loaders can be modified once they're created, and the classloader setup is all done before loading the eval script (in fact, the eval script is loaded using the very class loader that is being set up incorrectly to cause this bug).

Groovy does have some support for class loader modification with its 'grape' facility, and we do nothing in LensKit to deliberately interfere with that, so that *might* work.

At this point, the preferred way to modify the class loader in a configuration setting is with Gradle. Documentation and examples forthcoming (working on that shortly, actually).
