### ISSUE TITLE
Create general-purpose binary search class

### ISSUE THREAD

**Issue by mdekstrand** [lenskit/lenskit#684]
There are an increasing number of places in LensKit that would benefit from a general-purpose binary search class. This should work somewhat like fastutils's generic sort; searching a range of indexes, with an evaluator that takes an index, looks up the item there (from whatever source, be it a list or a buffer or whatever), and compares it to the target item. One potential design is as follows,

```java
public abstract class BinarySearch {
    public int search(int from, int to) {
        /* conduct binary search of range [from,to) */
    }

    /**
     * Test an index for the binary search.
     * @param index The index to test.
     * @return 0 if the item at the index is the one sought; < 0 if it is less than the one sought, and > 0 if it is greater than the one sought.
     */
    protected abstract int evaluate(int index);
}
```

There are several steps here:

- [x] Implement the utility class (in `org.grouplens.lenskit.util`).
- [x] Use it for the new limited DAOs (#662)

**Comment by elehack** [comment]
I think this class should also have a (static?) method to convert a failed search back to an insertion point.

**Comment by elehack** [comment]
I think this class should also guarantee that it will return the *first* matching item.

**Comment by mdekstrand** [comment]
Will be completed by #771.

**Comment by mdekstrand** [comment]
Done in #785.
