### ISSUE TITLE
topNRecallPrecision.properties (and possibly related files) out of date

### ISSUE THREAD

**Issue by taavi223** [lenskit/lenskit#685]
Right now, it points to: "builder=org.grouplens.lenskit.eval.metrics.topn.TopNRecallPrecisionMetric$Builder"

But it should point to the current class name, which is "PrecisionRecallTopNMetric"

The file itself should probably also be renamed to match the current class name.

**Comment by elehack** [comment]
Thanks. We should get this fixed for LensKit 2.2. You're right about the fix.

@taavi223, do you want to throw together a PR for it? If not, it won't take me very long to do it.

**Comment by taavi223** [comment]
I can try my hand at a pull request. When do you need it by?




Taavi Taijala

**Comment by kluver** [comment]
@taavi223 I don't think there is any huge rush. 
@elehack if this gets done after CSCW would that be a problem?

**Comment by elehack** [comment]
I hope to have 2.2 out by end of month; mostly ready by end of our spring break (which is next week).

However, I'm going to be mucking around in related code myself for the last 2.2 feature I'm developing, so I might just include the fix in those changes if you don't have time to get to it quickly (which is totally fine with me).

**Comment by taavi223** [comment]
You may just want to go ahead and take care of it then. It’ll probably take me until after spring break to get around to it.


Taavi Taijala

**Comment by elehack** [comment]
Fixed in 666846c and 2563c78.
