### ISSUE TITLE
Review and revise core API classes

### ISSUE THREAD

**Issue by mdekstrand** [lenskit/lenskit#732]
We need to review the core API classes (`ItemRecommender`, `RatingPredictor`, etc.). This is for two reasons:

- removing sparse vectors (#730) in favor of a new result API (#727) will make changes in what the APIs look like.
- the classes and APIs are not necessarily how we really want them

I think the following are, conceptually, probably about right:

- `ItemRecommender`
- `ItemScorer`
- `RatingPredictor`

I think we need to reconsider:

- `GlobalItemRecommender` could be come `RelatedItemFinder`
- `GlobalItemScorer` needs a better name, related to scoring items with respect to each other.

Then, for orthogonality, we can add:

- `RelatedUserFinder`
- A user-to-user scoring function

**Comment by mdekstrand** [comment]
This is partially done by #733. Still need to decide on global/related APIs.

**Comment by kluver** [comment]
On it. probable turn around: Thursday.

**Comment by mdekstrand** [comment]
With #790, this is now done.
