### ISSUE TITLE
Provide way to pre-load data to remove loading time from training time

### ISSUE THREAD

**Issue by mdekstrand** [lenskit/lenskit#821]
We should have a way to tell the evaluator to pre-fetch data so that the time reading data from disk is not considered in the training time of the algorithm. This is a problem because the first algorithm to read the data will have the extra training time induced by a cold cache.

For both the binary rating DAO and the text DAO, we could do a pre-scan of the ratings before training the model to warm up the OS caches/page tables.

This should be part of a broader 'timing mode' that turns off component caching so we can have accurate times.

**Comment by tiagoprojetos** [comment]
I believe that the best way is taking time before and after training. But it is not acceptable read from disk during training time. Because it inserts a not small constant (or not) time in each training time. So every data must be loaded in memory.
 
"This is a problem because the first algorithm to read the data will have the extra training time induced by a cold cache." ==> All the data should be loaded before ```config.addComponent(dao)```, i. e., in the constructor.

**Comment by mdekstrand** [comment]
Proposal: add a `prefetch` option to the train-test experiment, along with a `prefetch` method on data sources. If prefetching is turned on, then before training the model, the train-test experiment will ask the train data to prefetch itself.

- For text DAOs, prefetching will load the file content into an `EventCollectionDAO` and then use that DAO for subsequent retrieval.
- For binary rating DAOs, prefetching will do a scan over the ratings in the DAO to warm up the cache.

**Comment by mdekstrand** [comment]
For the text DAO warmup, we'll also want a way to garbage-collect the prefetched data. Proposal:

- At prefetch, save the warmed-up data.
- Register a timer to after some time (60 seconds?) replace the hard reference to the warmed-up data with a soft reference, so that it can be GCed.

**Comment by kluver** [comment]
Does this solve the general problem of cold caches. It was my understanding that there is a rich set of best practices around algorithm timing that involves a mandatory "burn in" period. that gets around JIT, that gets around data-structures inside the algorithm etc.

Do we want to look into something like that for this?

**Comment by mdekstrand** [comment]
For timing, there are 4 major issues of this form that I see:

- Data loading time. If each algorithm loads its own data, then the only variance between algorithms is the OS's cache status so comparisons are valid. However, it means counting data load in the training time.
- LensKit's component caching. That has to be disabled in order to time training.
- Parallelism. Since none of LensKit's algorithms are multithreaded, running in parallel with as many jobs as there are cores should be fine. Once LensKit grows multithreaded algorithms, we'll have to be careful about threading to obtain valid timings. Probably single-thread the evaluations.
- Java speed, particularly the JIT. This is super-important for microbenchmarks. However, I think we can safely ignore it for timing model builds. In a model build, the JIT will kick in pretty early in the process, and I expect that that, on the time scales we're looking at for model builds, the JIT time is negligable. If we want to reduce the amount of time spent on slow code before JITing, the experimenter can change the JVM's compile threshold. I don't think it's worth giving LensKit a burn-in for algorithm code, but might be persuadable otherwise. A burn-in should look like a train-test run of the algorithm on a small data set.

**Comment by tiagoprojetos** [comment]
If it use pagination for fit data in memory, the algorithm time probably asymptote HDD access time. It is more precise to compute time within algorithm execution, discounting data access time. It will be a robust time evaluation, independent of Event DAO.

**Comment by tiagoprojetos** [comment]
About Parallelism. It can also computing time within algorithm (like in the previuos comment) and sum up the execution time of all threads.

**Comment by tiagoprojetos** [comment]
I have some time date for ml-100k. Training time is the 2nd column, and test time the 3rd. The JIT increases the time of the first fold. Particularly for UBPea50



============================class algoritmos.SVD50===============
ttre = tempo de treinamento
tpre = tempo de predição
fold	ttre	tpre	RMSE	MAE	
1	PT10.939S	PT3.123S	0.9372603282077502	0.7307054081676979
2	PT12.686S	PT2.398S	0.9377407997413031	0.7331114018438892
3	PT11.893S	PT2.288S	0.937267017338036	0.7330420086773033
4	PT11.589S	PT2.192S	0.9354640046722601	0.7303359388350689
5	PT12.725S	PT1.962S	0.9395074555670988	0.7341291382747096

============================class algoritmos.IBCos===============
ttre = tempo de treinamento
tpre = tempo de predição
fold	ttre	tpre	RMSE	MAE	
1	PT2.938S	PT5.313S	0.9348074517638716	0.7364154631517984
2	PT2.506S	PT2.422S	0.936459705643959	0.740446151592217
3	PT2.207S	PT2.388S	0.9380642938507936	0.7368350970474584
4	PT2.326S	PT2.429S	0.940936036379305	0.7410138816087368
5	PT2.086S	PT2.275S	0.9417932094916974	0.7402436658140795

============================class algoritmos.IBPea===============
ttre = tempo de treinamento
tpre = tempo de predição
fold	ttre	tpre	RMSE	MAE	
1	PT3.854S	PT3.139S	0.950965647095874	0.7506000757986906
2	PT3.805S	PT2.317S	0.9528666375752372	0.7546152307756009
3	PT3.619S	PT2.244S	0.9531338940628409	0.7496975607577611
4	PT3.284S	PT2.376S	0.9565502733851552	0.7551752927652704
5	PT3.22S	PT2.446S	0.9584446844511934	0.7545952805557665

============================class algoritmos.UBCos50===============
ttre = tempo de treinamento
tpre = tempo de predição
fold	ttre	tpre	RMSE	MAE	
1	PT0.154S	PT3M41.957S	0.946978588293639	0.745969619892691
2	PT0.208S	PT3M21.131S	0.9470648053658841	0.7483247237230547
3	PT0.117S	PT4M46.403S	0.9493441369341852	0.7453106122204531
4	PT0.891S	PT4M2.058S	0.95221791668501	0.7495396054586712
5	PT0.162S	PT4M4.477S	0.9504830340353424	0.7480654259396055

============================class algoritmos.UBPea50===============
ttre = tempo de treinamento
tpre = tempo de predição
fold	ttre	tpre	RMSE	MAE	
1	PT0.153S	PT1H25M46.122S	1.0093345836536256	0.8008354910300571
2	PT1.226S	PT5M19.14S	1.0097431542916007	0.803438840117627
3	PT0.748S	PT49M45.824S	1.009125874806399	0.7966543508766137
4	PT1.056S	PT36M55.3S	1.0117075647048226	0.8029018389102996
5	PT4.056S	PT53M22.144S	1.0114370111741446	0.8012958746275244

**Comment by mdekstrand** [comment]
I have raised #822 to track the overall work on supporting reliable timing, so we can use this ticket to specifically focus on the data pre-fetching support.

**Comment by mdekstrand** [comment]
75e707b fixes this.
