### ISSUE TITLE
How to save ItemScorer scores?

### ISSUE THREAD

**Issue by Bionic1251** [lenskit/lenskit#868]
Is it possible in Lenskit 2.2.1 to print scores predicted by an algorithm to a file?
Evaluator’s function setPredictOutputPath produces file with predicted ratings of items. However, the ratings are clamped (limited by min max ratings). For example, if an algorithm predicts score 100, the corresponding printed rating will be 5.

**Comment by mdekstrand** [comment]
In your algorithm configuration, disable the preference domain:

```groovy
at (RatingPredictor) {
    bind PreferenceDomain to null
}
```

That will turn off the clamping.
