### ISSUE TITLE
Precision, Recall and NDCG seem inconsistent

### ISSUE THREAD

**Issue by Bionic1251** [lenskit/lenskit#871]
An algorithm with low user coverage has high Precision and Recall, but low NDCG. For example, on a sparse dataset ItemItemScorer often returns empty recommendation lists. Precision/Recall metric skips empty lists, while NDCG penalizes algorithms for this kind of suggestions.

**Comment by mdekstrand** [comment]
This is an interesting point — how should we handle empty recommendation lists? I agree that it should be consistent.

By the straightforward definition of nDCG, 0 seems appropriate: if nDCG measures the gain accumulated, an empty list accumulates no gain.

Similarly, an empty list has 0 recall, and undefined precision.

(These cases can be detected in post-evaluation analysis by examining the # of recommendations for the user)

Further thoughts welcome.

**Comment by Bionic1251** [comment]
In my opinion, empty lists should have a negative impact on precision and recall. In Lenskit 2 I fixed this problem as follows:

	public class PrecisionRecallTopNMetric…
	public Result doMeasureUser(TestUser user, Context context) {
		int tp = 0;

		LongSet items = goodItems.select(user);
		if (items.isEmpty()) {
			logger.warn("no good items for user {}", user.getUserId());
		}

		List<ScoredId> recs = user.getRecommendations(listSize, candidates, exclude);
		if (recs == null && recs.isEmpty()) {
			context.addUser(0, 0);
			logger.warn("no recommendations for user {}", user.getUserId());
			return null;
		}

**Comment by kluver** [comment]
In my opinion 1) precision and recall of an empty list should be zero 
(as no true positives occurred)

I would also, as a general rule,  always use a recommendation length 
metric (and a coverage metric for prediction evaluations). If there is 
significant under sized recommendation list related problems I think its 
fair to say an algorithm has failed, regardless of its other performance.

~kluver

**Comment by mdekstrand** [comment]
It seems we have that recall of an empty list should be 0.

My personal instinct would be to make precision of an empty list NaN when reporting it in the per-user output file; I could be persuaded that we should consider it a 0 when LensKit is doing its own aggregating, so that we are actually aggregating over all users. But we also need to think about how we aggregate for other metrics — if we can't predict anything for a user, including a 0 in aggregating their RMSE would be the wrong thing to do.

**Comment by mdekstrand** [comment]
I am fully convinced that they should both be 0.
