### ISSUE TITLE
cannot install lenskit on ubuntu

### ISSUE THREAD

**Issue by ChenKevin0123** [lenskit/lenskit#887]
i want to set up lenskit on ubuntu so i read this -- http://recsys.cs.umn.edu/linux.html.
it says 
"Download the LensKit binary archive from http://lenskit.grouplens.org/download.html(there's 404 error on this page), and unpack it (with tar xvf lenskit-2.0.tar.gz). The shell scripts run directly from the binary archive. For linking against LensKit when you build your assignments, Maven will automatically download LensKit from the Maven central repository."
i have install jdk and maven successfully. then i type "tar xvf lenskit-2.0-source.tar.gz "(i can't find lenskit-2.0.tar.gz on the internet or maybe "lenskit-2.0-source.tar.gz is what it called now).then  I tested if i installed it successfully---
root@ubuntu:/home/ckf# lenskit-eval --version
lenskit-eval: command not found
did i missed environment variables to set?if i did,please tell me how to set them.

**Comment by mdekstrand** [comment]
Thanks for your interest in LensKit!

Those instructions are very out-of-date and should be taken offline (I thought they had been, but I will go dos o more thoroughly).

The current download page is here: <http://lenskit.org/download/>

Most users do not need to download the binary package; rather, they use LensKit through Maven, Gradle, or other Maven-compatible Java build systems: http://lenskit.org/documentation/basics/getting-started/
