### ISSUE TITLE
Is it possible to integrate Lenskit with android application programmatically?? 

### ISSUE THREAD

**Issue by EsraaSalem** [lenskit/lenskit#903]
Is it possible to integrate Lenskit with android application programmatically??

**Comment by mdekstrand** [comment]
It is certainly possible to have an Android application connect to a web service that is using LensKit to provide recommendations. I think this will likely be the most common way to construct a LensKit-powered Android application.

As far as running LensKit itself on Android, I do not know if it is possible or not. We have not tested it. It depends on whether Dalvik supports enough reflection for Grapht to function and provides the Java 7 APIs that LensKit uses. LensKit 2 is more likely to work, as it is compatible with Java 6.

**Comment by kluver** [comment]
@Ekstrand,

Wouldn't be possible to build lenskit objects without grapht? Its a much 
bigger pain, but I feel like I've built that object graph by hand on at 
least one occasion.

~Kluver

**Comment by EsraaSalem** [comment]
what is "grapht" can you clarify more?

**Comment by mdekstrand** [comment]
@EsraaSalem [Grapht](http://grapht.grouplens.org) is the dependency injection framework that we use to configure and instantiate LensKit objects.

@kluver It is likely possible, but quite painful.
