### ISSUE TITLE
Investigate switching to LA4J

### ISSUE THREAD

**Issue by mdekstrand** [lenskit/lenskit#982]
Do we want to switch from [Commons Math](http://commons.apache.org/proper/commons-math/) to [LA4J](http://la4j.org/)?

We would lose some of the math functions - solvers, etc. - but I have never gotten them to work well. We would get a simpler interface, I think. I do not know how performance would change.

Would welcome input from @kluver @qian2015 @jdekstrand.

**Comment by mdekstrand** [comment]
Would also welcome input from anyone else, to be clear.

**Comment by qian2015** [comment]
I generally tend to vote towards staying with Commons Math for now. I guess it depends on whether Commons Math is blocking something (only switching to LA4J fulfills it). I think there are higher priority things to do. Also, Commons Math is relatively more mature and active than LA4J. 

* Note: Samantha is using Commons Math and found it good enough. I compared with LA4J before and found the doc not complete. But, it seems that it has changed now.

**Comment by mdekstrand** [comment]
@qian2015 Thanks for your input and experience report! We will plan to stick with Commons Math unless we have a compelling reason otherwise.

The appealing thing I was seeing was LA4J's more traditional sparse matrix support: compressed sparse row/column storage. Commons Math also has some long-standing weaknesses like no ability to compute truncated SVDs (which was closed as 'Won't Fix' after no movement for a long time). But LA4J doesn't fix that particular problem either.
